# -*- fill-column: 76; -*-
#+TITLE: Experiment01 - Accessing data at packet end
#+OPTIONS: ^:nil

This example shows how to access BPF packet data at XDP =data_end=.
Examples like this are needed, as the programmer needs to convince the
BPF verifier that access bounds are safe.

* Use-case: tail-grow timestamping

The BPF helper =bpf_xdp_adjust_tail= is being extended with
capabilites to grow the packet size at tail.  To use this for
anything, we need to demo how to access packet data at XDP =data_end=.

One use-case is to *add timestamps in extended tailroom* at XDP
processing time, which will survive when packet is processed by
network-stack (via XDP_PASS).  One way to capture this timestamp is to
use =tcpdump=, which could use this to determine the time spend in
network-stack (on NIC without hardware timestamps).

In main example [[file:xdp_prog_kern.c]], the =xdp_tailgrow_parse= code
implements this by parsing up-to the IP-layer, and using the
IP-headers total-length field ([[https://elixir.bootlin.com/linux/v5.6.10/source/include/uapi/linux/ip.h#L97][iphdr->tot_len]]).  See the code for the
strange bounding checks needed to convince the verifier.  Notice, this
is limited to IPv4 ICMP packets for testing purposes.

** Side-note: extra programs

Side-note: [[file:xdp_prog_kern.c]] also contains some other smaller
programs to test =bpf_xdp_adjust_tail= grow works, and to benchmark
the overhead when doing =XDP_TX=.  Selecting others BPF programs via
=xdp_loader= option =--prog== like this:

#+begin_src sh
 sudo ./xdp_loader --dev mlx5p1 --force --prog xdp_tailgrow
 sudo ./xdp_loader --dev mlx5p1 --force --prog xdp_tailgrow_tx
#+end_src
